-- MySQL Script generated by MySQL Workbench
-- Wed Mar  9 12:56:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema php-moderno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php-moderno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php-moderno` DEFAULT CHARACTER SET utf8 ;
USE `php-moderno` ;

-- -----------------------------------------------------
-- Table `php-moderno`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php-moderno`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 2,
  `permissao` TINYINT(1) NOT NULL DEFAULT 2,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php-moderno`.`atualizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php-moderno`.`atualizacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atualizacao_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_atualizacao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `php-moderno`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
